newrelic/node-newrelic-aws-sdk

lib/core.js
tests/versioned/common.js
tests/versioned/package.json
tests/versioned/s3.tap.js

* Added instrumentation for http externals, starting with S3.

NODE-1956 Instrument S3

---

tests/versioned/dynamodb.tap.js

Updated DynamoDB tests to call `createTable` with the table name `StaticTestTable-DO_NOT_DELETE`, which exists on AWS, so we no longer have to wait for a table to be created each run. Table items are dynamically created and deleted, and `deleteTable` is called with a fake table name.

update DynamoDB tests

---

tests/versioned/common.js
tests/versioned/http-services.tap.js
tests/versioned/package.json
tests/versioned/s3.tap.js

This adds tests for the services we will record as http externals.

Added tests for all http-based services

---

CHANGELOG.md

* Added instrumentation for services to be recorded as HTTP externals.
* APIGateway
* ELB
* ElastiCache
* Lambda
* RDS
* Redshift
* Rekognition
* S3
* SES

Updated changelog for v0.1.0

---

lib/dynamodb.js
lib/instrumentation.js
lib/sns.js
tests/versioned/sns.tap.js

* Added initial SNS instrumentation.

NODE-1960 add SNS outbound instrumentation

---

.gitignore
lib/instrumentation.js
lib/sqs.js
package.json
tests/versioned/common.js
tests/versioned/sqs.tap.js

* Added initial instrumentation for SQS sendMessage, sendMessageBatch and receiveMessageBatch APis.
~Still needs integration test but throwing out there for perusal/usage in the meantime.~

NODE-1959 Adds initial instrumentation for SQS

---

.github/PULL_REQUEST_TEMPLATE.md

Added GitHub PR template

---

CODE_OF_CONDUCT.md

- Updates code of conduct to use new standard language

#40 Updates Code of Conduct

---

index.js
lib/core.js
lib/dynamodb.js
lib/instrumentation-helper.js
lib/instrumentation.js
lib/sns.js
lib/sqs.js
lib/util.js
nr-hooks.js
tests/unit/util.tap.js
tests/versioned/amazon-dax-client.tap.js
tests/versioned/aws-sdk.tap.js
tests/versioned/common.js
tests/versioned/dynamodb.tap.js
tests/versioned/http-services.tap.js
tests/versioned/instrumentation-supported.tap.js
tests/versioned/instrumentation-unsupported.tap.js
tests/versioned/newrelic.js
tests/versioned/s3.tap.js
tests/versioned/sns.tap.js
tests/versioned/sqs.tap.js

- Added copyright to all source files.
- #45

#45 Copyright to All Source Files

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/troubleshooting.md

- Adds issues and enhancement templates
- #41

#41 Adds Issue Templates

---

package.json

- Bumped @newrelic/test-utils to 4.0.0
- #45

Issue #54: Bumping Test Utils Dependency

---

CONTRIBUTING.md

Updates contributing guidelines

---

THIRD_PARTY_NOTICES.md
package.json
third_party_manifest.json

Updated the third party manifest and third party notices.
Bumped the newrelic nodejs agent dependency to 6.11.0.
Closes: #37

Update third party notices and bump newrelic dependency

---

THIRD_PARTY_NOTICES.md

Adds footer to third party notices
Closes: #63

Adds footer to third party notices

---

README.md

- Updated README.md 
- Part of Issue #47.  
Doesn't add build badges -- that will be handled by https://github.com/newrelic/node-newrelic-aws-sdk/issues/66

Adds new README.md based on Current Template

---

.npmignore

* Added additional items to .npmignore.

Adds additional items to .npmignore.

---

README.md

Fixes: https://github.com/newrelic/node-newrelic-aws-sdk/issues/66
* Updates CI badge.
* Fixes misspelling.
* Removes "remove" language.
* Restructures some language to go better together in sections.
* Adds additional docs link.
* Updates description of what our instrumentation supports.
* Updates security link to be more future proof.

Readme updates to update CI badge and other items.

---

LICENSE

Fixes first-line indentation of license file.

---

README.md

- Updated readme with community-plus header based on repolinter suggestion.
- Closes: #76

Updated readme with community-plus header

---

.github/workflows/ci-workflow.yml

Adds Node 14 to CI.

---

.github/workflows/ci-workflow.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
package.json
tests/versioned/package.json

- Remove Node v8.x support
- Remove Code of Conduct doc and link to New Relic org Code of Conduct in Contributing doc.

Remove node 8 support

---

CHANGELOG.md
THIRD_PARTY_NOTICES.md
third_party_manifest.json

* Removed Node v8.x from CI.
* Added Node v14.x to CI.
* Update README for consistency with New Relic OSS repositories
* Remove Code of Conduct doc and link to New Relic org Code of Conduct in
Contributing doc.

Release v3.0.0

---

lib/dynamodb.js
tests/versioned/package.json

Fixes #83
* Properly instrument dynamodb batchGet, batchWrite, transactGet, and transactGet calls as database operations instead of External service calls
```js
batchGet: function(params, callback) {
var operation = this.serviceClientOperationsMap['batchGet'];
return this.makeServiceRequest(operation, params, callback);
},
batchWrite: function(params, callback) {
var operation = this.serviceClientOperationsMap['batchWrite'];
return this.makeServiceRequest(operation, params, callback);
},
transactWrite: function(params, callback) {
var operation = this.serviceClientOperationsMap['transactWrite'];
return this.makeServiceRequest(operation, params, callback);
},
transactGet: function(params, callback) {
var operation = this.serviceClientOperationsMap['transactGet'];
return …
```

Instrument batchGet/batchWrite/transactGet/transactWrite

---

CHANGELOG.md
third_party_manifest.json

* Properly instrument dynamodb batchGet, batchWrite, transactGet, and transactGet calls as database operations instead of External service calls.
#84

Release v3.1.0

---

package.json

* Bumped @newrelic/test-utilities to ^5.1.0.

Bumped @newrelic/test-utilities to ^5.1.0.

---

package.json
tests/versioned/amazon-dax-client.tap.js
tests/versioned/aws-sdk.tap.js
tests/versioned/dynamodb.tap.js
tests/versioned/http-services.tap.js
tests/versioned/instrumentation-supported.tap.js
tests/versioned/instrumentation-unsupported.tap.js
tests/versioned/s3.tap.js
tests/versioned/sns.tap.js
tests/versioned/sqs.tap.js

Upgrades tap to ^15.0.9

---

.github/workflows/ci-workflow.yml
package.json

Added Node 16 to CI

---

CHANGELOG.md

* Added versioned tests to the files list within package.json
https://github.com/newrelic/node-newrelic-aws-sdk/pull/93

release v4.0.1

---

index.js
lib/v3-sns.js
nr-hooks.js
tests/versioned/aws-sdk-v3/sns.tap.js
tests/versioned/aws-server-stubs/response-server/index.js

* Updated approach to instrument the `SNSClient` by leveraging a middleware to properly time the sns `PublishCommand`
This is a rev 2 of #102.

updates the sns instrumentation based on the onResolved hook

---

.github/workflows/prepare-release.yml

* Added workflow to automate preparing release notes by reusing the `newrelic/node-newrelic/.github/workflows/prep-release.yml@main` workflow from agent repository.

Added workflow to prepare release

---

.github/workflows/create-release.yml

* Added a Create Release workflow that uses the `release-creation.yml` from the agent repo.
This is untested but _should_ work.  I will adjust after it is used the first time.

added create release workflow 🎉

---

package-lock.json

* Resolved several dev-dependency audit warnings.

Resolves several dev npm audit warnings.

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Removed versioned tests from npm artifact.
* Part of [#1027](https://github.com/newrelic/node-newrelic/issues/1027)

packages: remove versioned tests

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
tests/versioned/v2/dynamodb.tap.js
tests/versioned/v3/client-dynamodb.tap.js
tests/versioned/v3/lib-dynamodb.tap.js
third_party_manifest.json

* Removed usage of `async` module.

Removes usage of async module.

---

package-lock.json
package.json
tests/versioned/v2/package.json
tests/versioned/v3/package.json
third_party_manifest.json

Signed-off-by: mrickard <maurice@mauricerickard.com>
Updated Node engine in `package.json`, `tests/versioned/v2/package.json`, and `tests/versioned/v3/package.json` for minimum version 14.
https://issues.newrelic.com/browse/NR-35639
Updated Node engine in `package.json`, `tests/versioned/v2/package.json`, and `tests/versioned/v3/package.json` for minimum version 14.

Dropped Node 12

---

.c8rc.json
.github/workflows/ci-workflow.yml
README.md
THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

https://app.codecov.io/gh/newrelic/node-newrelic-aws-sdk/tree/NR-60705-codecov/
* Updated tests to use c8
* Added codecov upload to CI build
* Added badges 🙌🏻

NR-60705 wire up c8 and codecov for coverage collection

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
tests/versioned/v3/package.json
third_party_manifest.json

We have a customer reporting a crash with 3.202.0 but I cannot reproduce. Now that the problem version is gone we can unleash the versions again.

updated versions tests to test v3 vesions > 3.194.0 as AWS seems to have fixed their issues

---

tests/versioned/v3/sns.tap.js

* https://github.com/newrelic/node-newrelic/pull/1541
* https://issues.newrelic.com/browse/NEWRELIC-7612
This will have to be merged before the PR in agent is done(https://github.com/newrelic/node-newrelic/pull/1550).

NEWRELIC-7612 removes assertion of the x-newrelic-disable-dt header as we can no longer remove this to prevent crashes in AWS SDK

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

Updated agent and test utils to latest as dev deps for testing posterity.

updated agent and test utils to latest

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
tests/versioned/v2/package.json
tests/versioned/v3/package.json
third_party_manifest.json

* **BREAKING**: Removed support for Node 14. 
Closes #201 
Closes NR-142059

chore!: Dropped Node 14

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

Upgraded test utils, newrelic so that the agent can remove the unused shimmer.patchModule and shimmer.unpatchModule.

chore: updated @newrelic/test-utilities to latest

---

lib/v3/smithy-client.js
tests/versioned/v3/lib-dynamodb.tap.js

* Updated v3 smithy-client instrumentation to properly handle all types of clients for DynamoDB, SQS, and SNS. 
Closes #208
When the instrumentation was ported in #205 to only register relevant middleware if the client sending matched `this.constructor.name`.  This provided gaps because all the libraries we instrument: `@aws-sdk/client-sns`, `@aws-sdk/client-sqs`, `@aws-sdk/client-dynamodb`, `@aws-sdk/lib-dynamodb` have other classes that were not getting matched.  This updates the matching by stripping `Client` from the end of every constructor.

fix: updated smithy-client instrumentation to properly handle all types of clients for dynamo, sqs, sns

---

package-lock.json
package.json
third_party_manifest.json

* Removed `newrelic` as peer dependency since this package only gets bundled with agent.

chore: removed newrelic as peer dep as standalone is no longer supported

---

lib/llm/bedrock-command.js
lib/llm/bedrock-response.js
lib/llm/chat-completion-summary.js
tests/unit/llm/bedrock-command.tap.js
tests/unit/llm/bedrock-response.tap.js
tests/unit/llm/chat-completion-summary.tap.js
tests/versioned/aws-server-stubs/ai-server/index.js
tests/versioned/aws-server-stubs/ai-server/responses/index.js
tests/versioned/aws-server-stubs/ai-server/responses/llama2.js
tests/versioned/v3/bedrock-chat-completions.tap.js

feat: Add LLama2 support to LLM events and mock server

---

THIRD_PARTY_NOTICES.md
lib/v3/bedrock.js
package-lock.json
package.json
tests/versioned/v3/bedrock-chat-completions.tap.js
third_party_manifest.json

This pr records a metric on every`InvokeModelCommand`. 
Added a new versioned test
Closes #227

feat: Record metric on every InvokeModelCommand

---

lib/util.js
lib/v3/bedrock.js
tests/versioned/v3/bedrock-chat-completions.tap.js
tests/versioned/v3/bedrock-embeddings.tap.js

Add llm: true attribute to Transactions that contain llm spans.
Added versioned tests
Closes #243

feat: Add llm attribute to all transactions that contain llm spans for bedrock

---

.github/workflows/prepare-release.yml

Please provide a brief description of the changes introduced in this pull request.
What problem does it solve? What is the context of this change?
Please describe how you have tested these changes. Have you run the code against an example application?
What steps did you take to ensure that the changes are working correctly?
Please include any related issues or pull requests in this section, using the format `Closes #<issue number>` or `Fixes #<issue number>` if applicable.

ci: fixed misspelling in prepare-release.yml

---

lib/v3/bedrock.js
tests/versioned/v3/bedrock-chat-completions.tap.js
tests/versioned/v3/bedrock-embeddings.tap.js
tests/versioned/v3/bedrock-negative-tests.tap.js

Feature flag was added in case we had to make a patch release of aws sdk while we were working on bedrock instrumentation.  That was not the case so removing.

refactor: Removed aws_bedrock_instrumentation feature flag as feature is ready

---

lib/llm/event.js
lib/util.js
lib/v3/bedrock.js
tests/unit/llm/chat-completion-message.tap.js
tests/unit/llm/chat-completion-summary.tap.js
tests/unit/llm/embedding.tap.js
tests/unit/llm/event.tap.js
tests/versioned/common.js
tests/versioned/v3/bedrock-chat-completions.tap.js
tests/versioned/v3/bedrock-embeddings.tap.js

chore: Apply LLM updates based on specification changes

---

lib/llm/chat-completion-message.js
lib/llm/chat-completion-summary.js
lib/llm/event.js
lib/v3/bedrock.js
tests/unit/llm/chat-completion-message.tap.js
tests/unit/llm/chat-completion-summary.tap.js
tests/unit/llm/event.tap.js
tests/versioned/common.js

chore: Refactor LLM user added metadata

---

lib/v3/bedrock.js
tests/versioned/v3/bedrock-chat-completions.tap.js

Handle when `ai_monitoring.streaming.enabled` is false. It should only increment the supportability metric, assign llm to tx and increment tracking metric.
Closes #254

feat: Added ability to disable instrumenting streaming via `ai_monitoring.streaming.enabled` = `false`

---

lib/util.js
lib/v2/dynamodb.js
lib/v2/sns.js
lib/v2/sqs.js
lib/v3/bedrock.js
lib/v3/dynamodb.js
lib/v3/sns.js
lib/v3/sqs.js
tests/unit/util.tap.js
third_party_manifest.json

This cannot be merged until the agent makes a release. The CI will fail because specs are not on the shim instance in a released version of agent yet. 
To test locally
```
npm link
npm link newrelic
npm test
```
Closes #258

refactor: Updated aws sdk instrumentation to construct specs at instrumentation

---

lib/llm/chat-completion-message.js
lib/llm/embedding.js
tests/unit/llm/chat-completion-message.tap.js
tests/unit/llm/embedding.tap.js
tests/versioned/v3/bedrock-chat-completions.tap.js
tests/versioned/v3/bedrock-embeddings.tap.js

Adds ability to disable capturing of content in events.
Closes #262

feat: Added ability to disable capturing of content in LLM events `ai_monitoring.record_content.enabled`

---

lib/llm/chat-completion-message.js
lib/llm/embedding.js
tests/unit/llm/chat-completion-message.tap.js
tests/unit/llm/embedding.tap.js
tests/versioned/common.js
tests/versioned/v3/bedrock-embeddings.tap.js

chore: Updated Bedrock entities with token_count

---

package-lock.json

Ran `npm install` to sync package and package lock file in order to finish releasing.

chore: Sync package-lock.json with package.json file
