lib/core.js
tests/versioned/common.js
tests/versioned/s3.tap.js

Added `aws.service` and `aws.region` attributes. The second attribute is not necessary by spec yet, but was easy enough to add and python is considering it too.

Added aws.service and aws.region attributes

---

lib/dynamodb.js
tests/versioned/dynamodb.tap.js

* Moved `name` property to the root of DynamoDB segment description object.
Previously, segments were being incorrectly named `"Datastore/operation/DynamoDB/undefined"`, due to the operation name being misplaced.

dynamodb: move name prop to segment description root

---

lib/dynamodb.js
tests/versioned/dynamodb.tap.js

* Adds support for DocumentClient API calls to be captured as Datastore segments/metrics. 
Supported calls are: `get`, `put`, `update`, `delete`, `query` and `scan`. These will be named according to the underlying DynamoDB operation that is executed. For example: `get` will be named `getItem`. DocumentClient calls not listed above will still be captured as Externals.
* Fixed issue that would prevent multiple DynamoDB instances from being instrumented.

NODE-2030 Adds DocumentClient instrumentation

---

.travis.yml
package.json

* **BREAKING** Removed support for Node 6, 7, and 9.
The minimum supported version is now Node v8. For further information on our support policy, see: https://docs.newrelic.com/docs/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.

NODE-2185 Drop Node 6 support

---

CHANGELOG.md

* **BREAKING** Removed support for Node 6, 7, and 9.
The minimum supported version is now Node v8. For further information on our support policy, see: https://docs.newrelic.com/docs/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.

Release v1.0.0.

---

.npmignore

* Adds `.nyc_output` and `.vscode` to `.npmignore` to reduce chance of deploying unnecessary files to npm.
------
Noticed these during dry run of the previous release.

Adds additional items to npmignore to reduce chance of deployed cruft.

---

tests/versioned/package.json

* Bumps minimum versioned test Node version to 8+.
----
Missed this before thinking it was captured in a different PR. I am bad and should feel bad.

Bumps minimum versioned node engine to 8.

---

tests/versioned/package.json

* Limited versioned test permutations to one older version and then new versions going forward.
This is sort of a temporary fix for how quickly `aws-sdk` pushes updates. We'll get to a large permutation again and will likely eventually want to find a solution that automatically makes sense in the versioned runner but don't want to rush that.
This is easy enough to tweak on the fly.
Choosing the one original supported version just in case there's something that changes we *might* break down the road. Otherwise, they are releasing so fast I just chose the release from today. They seem to be releasing almost every work day.

Limits versioned tests to one older version and then newer versions going forward

---

lib/instrumentation-helper.js
lib/instrumentation.js
tests/versioned/instrumentation-supported.tap.js
tests/versioned/instrumentation-unsupported.tap.js
tests/versioned/package.json

Re: https://github.com/newrelic/node-newrelic-aws-sdk/compare/astorm/fix-old-versions?expand=1
Implements a simple feature sniffer in instrumentation that looks for required object properties before attempting to apply instrumentation.  Should fix _Cannot read property '[foo]' of undefined_ of undefined errors.  
If this simple pilot works well we should consider expanding it to sniff features for each aws instrumentation and/or formalize something like this into the shimmer system.

Feature Sniff for Features before Instrumenting

---

tests/versioned/common.js
tests/versioned/dynamodb.tap.js

* Adds external segment checking to ensure aren't capturing externals for instrumented datastore methods (callback style).
* Updates DynamoDB testing to leverage new dynamically generated table instead of needing a permanent one.

DDB test cleanup

---

.eslintrc
lib/core.js
tests/.eslintrc
tests/versioned/common.js
tests/versioned/dynamodb.tap.js
tests/versioned/package.json
tests/versioned/s3.tap.js
tests/versioned/sns.tap.js
tests/versioned/sqs.tap.js

* Adds official support for API promise calls. 
For example: `await ddb.createTable(params).promise()`.
* Fixed issue where external spans/segments would be incorrectly created in addition to more specific types such as datastore spans/segments. This also resulted in missing attributes from the more specific spans/segments.
* Fixed issue where spans/segments would not have timing update appropriately upon promise resolution. These would show sub-millisecond execution time as the time captured was the execution of the initial function not accounting for async execution.

Resolve promise issues

---

tests/versioned/dynamodb.tap.js

* Bumps DynamoDB `tap.test` timeout to avoid versioned test terminations when table creates are slow.
Didn't see this behavior prior but did see for the branches w/ the last release upon completion as well as when tried to roll new module into agent. Tested via `npm link` and seems to resolve locally, at least.
Unfortunately, because we run tests from the modules themselves, this will require another deploy.

Bumps DynamoDB tap.test timeout to avoid versioned test terminations

---

lib/dynamodb.js
tests/versioned/amazon-dax-client.tap.js
tests/versioned/common.js
tests/versioned/package.json

* Fixed issue where instrumentation would crash pulling `host` and `port` values when `AmazonDaxClient` was used as the service for `DocumentClient.`
`AmazonDaxClient` requests will report 'unknown' for `host` and `port` attributes. Other oddities may still exist until DAX officially supported.
------
See issue: https://github.com/newrelic/node-newrelic/issues/321

NODE-2187 Fix crash with DAX client

---

lib/sqs.js
lib/util.js
tests/unit/util.tap.js

This PR fixes a [customer reported error](https://github.com/newrelic/node-newrelic/issues/357) where the lack of a `QueueURL` parameter can cause a `TypeError: Cannot read property 'lastIndexOf' of undefined` error.   
It also moves the `grabLastUrlSegment` function into a utility library to allow for more straightforward unit testing of this method.

node-newrelic-357: Fix lastIndexOf Errors

---

CHANGELOG.md

* Fixes issue where instrumentation would produce a `TypeError: Cannot read property 'lastIndexOf' of undefined` error if a program called `sqs.receiveMessage` without a `QueueUrl` parameter.

Release v1.1.3

---

tests/versioned/amazon-dax-client.tap.js
tests/versioned/aws-sdk.tap.js
tests/versioned/aws-server-stubs/dynamodb-server/index.js
tests/versioned/aws-server-stubs/empty-response-server/index.js
tests/versioned/aws-server-stubs/index.js
tests/versioned/aws-server-stubs/sqs-server/index.js
tests/versioned/aws-server-stubs/sqs-server/responses/create-queue-response.xml
tests/versioned/aws-server-stubs/sqs-server/responses/receive-message-response.xml
tests/versioned/aws-server-stubs/sqs-server/responses/send-message-batch-response.xml
tests/versioned/aws-server-stubs/sqs-server/responses/send-message-response.xml
tests/versioned/common.js
tests/versioned/dynamodb.tap.js
tests/versioned/http-services.tap.js
tests/versioned/package.json
tests/versioned/s3.tap.js
tests/versioned/sns.tap.js
tests/versioned/sqs.tap.js

* Removed AWS servers as dependency for versioned tests.
Enables versioned test to run successfully for forked repo PRs.
Part 1 of 2 for: https://github.com/newrelic/node-newrelic-aws-sdk/issues/42
This makes it so we'll be able to run versioned tests on forked PR's in CI system. After this is landed, will be able to setup GitHub actions CI.
The most popular frameworks/libraries used for testing all didn't seem to work for one reason or another. Which was very sad. They either mocked too early (didn't hit our service instrumentation) or were inconsistent with returns (SQS). On the plus side, our needs were actually pretty limited based on what we were testing.
Current solution: custom http servers to mimic AWS servers. Most use a very generic server that returns empty success responses. …

Remove AWS servers as dependency for versioned tests

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Upgraded `@newrelic/test-utilities` to enable running 1 file through versioned runner
I had needs to just run 1 file so it can be achieved by now running
```sh
npx versioned-tests --minor --all -i 2 tests/versioned/aws-sdk-v3/<file>.tap.js
```

upgraded test utils to run a file

---

lib/v3-dynamodb-doc-client.js
nr-hooks.js
tests/versioned/aws-sdk-v3/dynamo-doc-client.tap.js
tests/versioned/aws-sdk-v3/package.json

* Added instrumentation to support DynamoDB Document Client(`@aws-sdk/lib-dynamodb`)
Closes #101 
This code might be able to go away once we see how all the instrumentation works with #108.  To use the document client you have to pass in client.  I haven't tested yet but the document client may still record operations implicitly with the client.

added instrumentation for the lib-dynamodb document client.  

---

THIRD_PARTY_NOTICES.md
index.js
nr-hooks.js
package-lock.json
package.json
third_party_manifest.json

…r v3 instrumentation
* Required agent version to be `>=8.7.0` to register the instrumentation to support AWS SDK v3
Closes #117 
I tested this against using module directly as well as within agent.
**Directly in app**
```sh
npm link # in aws-sdk
npm link @newrelic/aws-sdk # in app
node -r @newrelic/aws-sdk /path/to/app.js
```
**Within agent**
```sh
npm link # in aws-sdk
npm link @newrelic/aws-sdk # in agent
npm link # in agent
npm link newrelic # in app
node -r newrelic path/to/app.js
```
Both logged entry below when agent was not 8.7.0
```json
{"v":0,"level":40,"name":"newrelic","hostname":"C02F81D3MD6P","pid":37707,"time":"2022-01-05T16:22:37.559Z","msg":"Th       e New Relic Node.js agent must be >= 8.7.0 to instrument AWS SDK v3, current version: 8.6.0","component":"Transaction …
```

added semver check on agent for v3 instrumentation

---

lib/v3/check-agent-compatible.js
nr-hooks.js

* Fixed issue where v3 instrumentation checks against agent version would result in a logged error and fail to apply instrumentation.
* Fixes: https://github.com/newrelic/node-newrelic-aws-sdk/issues/121
This adds a special handle to each onResolved that checks the appropriate version and logs a warning specific to each module when the check fails. On failure, it clears out `onResolved` which avoids some execution including allocating another `shim` instance each time. Not huge but some savings and avoids logging multiple times (although could use warnOnce for that). On success, it replaces the `onResolved` with the original and then invokes the original.
Tried to implement in a way that is easy to rip out next major release.
Example logged failures for `8.6.0`:
```
... "msg":"Agent …
```

Fixes nr-hooks version checking circular reference issue.

---

tests/versioned/v3/package.json

* Limited versions tested for several clients that run through the generic external segment instrumentation.
When running full versioned, the v3 tests take significantly longer
than v2 cause now we are hitting so many distinct library versions.
Several of these are just exercising our generic instrumentation to
track as an external so reducing permutations there.
Left a couple of the seemingly more important ones up at 5.

Lowered amount of versions we test for clients that end up with generic external segments

---

tests/versioned/v3/package.json

* Locked down version of aws-sdk/client-s3 to under 3.192.0, as that version is broken
https://github.com/aws/aws-sdk-js-v3/issues/4053
Version 3.192.0 released today and is busted, so until https://github.com/aws/aws-sdk-js-v3/issues/4053 is fixed, we're locking down to lower versions in the versioned tests to fix CI. Once this bug is addressed we will revert this change.

Temporarily lock down version of @aws-sdk/client-s3

---

tests/versioned/v3/package.json

Update test semver range for client-s3 to exclude version 3.192.0
https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.193.0
Follow up from #152 now that AWS has released a new version

Update s3-client semver range to skip 3.192.0

---

tests/versioned/v3/package.json

* Updated versioned tests to exclude 3.194.0 from tests that rely on custom endpoints
https://github.com/aws/aws-sdk-js-v3/issues/4076
aws-sdk@3.194.0 broke support for custom endpoints, so stay with 3.193.0 until a fix comes out, at which point we'll have to update the semver ranges again

Update versioned tests to skip 3.194.0

---

tests/versioned/v3/package.json

https://github.com/newrelic/node-newrelic/actions/runs/3316187118/jobs/5477685877
I was trying to not be invasive with changes, but there have now been three different broken versions, so lock down everything until the sdk has balanced out again

Lock down all packages to max v3.193.0

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/troubleshooting.md
.github/workflows/ci-workflow.yml
.github/workflows/repolinter.yml

I just happen to notice this while waiting for the [agent to be released](https://github.com/newrelic/node-newrelic/actions/runs/3315379709).
Github actions removed [Node 12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) as a runner.  This PR fixes all instances that rely on Node.js 12.

update actions that are using deprecated node 12

---

tests/versioned/v2/instrumentation-supported.tap.js
tests/versioned/v2/instrumentation-unsupported.tap.js

I want to remove this magic property in the agent and replace it with a proper symbol. Having it in this test is cramping my style.
* Removed one usage of `__NR_instrumented` in the tests.
* NEWRELIC-4422

NEWRELIC-4422: remove usage of __NR_instrumented in tests

---

lib/v3/dynamodb-util.js
tests/versioned/common.js
tests/versioned/v2/amazon-dax-client.tap.js
tests/versioned/v2/aws-sdk.tap.js
tests/versioned/v2/dynamodb.tap.js
tests/versioned/v2/http-services.tap.js
tests/versioned/v2/instrumentation-supported.tap.js
tests/versioned/v2/instrumentation-unsupported.tap.js
tests/versioned/v2/s3.tap.js
tests/versioned/v2/sns.tap.js
tests/versioned/v2/sqs.tap.js
tests/versioned/v3/api-gateway.tap.js
tests/versioned/v3/client-dynamodb.tap.js
tests/versioned/v3/elasticache.tap.js
tests/versioned/v3/elb.tap.js
tests/versioned/v3/lambda.tap.js
tests/versioned/v3/lib-dynamodb.tap.js
tests/versioned/v3/package.json
tests/versioned/v3/rds.tap.js
tests/versioned/v3/redshift.tap.js
tests/versioned/v3/rekognition.tap.js
tests/versioned/v3/s3.tap.js
tests/versioned/v3/ses.tap.js
tests/versioned/v3/sns.tap.js
tests/versioned/v3/sqs.tap.js

* Fixed a crash when using versions >3.192.0 of AWS sdk v3 where a customer would see an error of `error: TypeError: config.endpoint is not a function`. 
* Closes NEWRELIC-5073
* AWS sdk team released a [breaking change in semver minor](https://github.com/aws/aws-sdk-js-v3/issues/4122)
* Closes #160 
I added a new test that does not pass in endpoint as our versioned tests did not catch this due to changes in the aws sdk.  You can read the linked GitHub thread but the AWS sdk team removed `config.endpoint` if you do not pass in a custom endpoint.  We will now derive the endpoint from region if `config.endpoint` is not a function.  I also tweaked how we register instrumentation to rely on `nr-hooks.js` to test how the agent registers code.

Add defensive code around retrieving endpoint

---

tests/versioned/v3/package.json

Pinned tests to versions before breaking change in aws-sdk 3.290.0.
https://issues.newrelic.com/browse/NEWRELIC-7497
aws-sdk 3.290.0 introduced automatic lowercasing of all header names, which interfered with instrumentation. Temporarily skipping this version to unblock other repos that depend on this package.

Skipping aws-sdk version 3.290.0

---

index.js
nr-hooks.js

* Assigned shimName to v3 instrumentation to avoid duplicate middleware crashes.
Closes #181
onResolved hooks + wrapClass do not play nicely in v10 of the agent.  onResolved hooks _could_ fire more than once unlike onRequired which typically gets the exported module from require cache.  [wrapClass](https://github.com/newrelic/node-newrelic/blob/main/lib/shim/shim.js#L744) was wrapping wraps of wraps of wraps, there's no end. This causes the instrumentation to fire n times for a given class now.  The solution is to assign the `shimName` to all aws instrumentation.  This will assign all of our instrumentation the same shim id and will restore legacy functionality of isWrapped. This is very difficult to reproduce in our versioned tests but if you follow the linked bug it is easy to repro.

fix: Assigned shimName to v3 instrumentation to avoid duplicate middleware crashes

---

tests/versioned/v2/package.json

Version [2.1372.0](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#213720) of aws sdk has broken both our instrumentation and mock server. I will file a ticket to address but want to unblock CI.

chore: prevent testing on version 2.1372.0+ of aws-sdk as it has broken our instrumentation and mock server

---

tests/versioned/v2/package.json
tests/versioned/v3/package.json

- chore: prevent testing on version 2.1372.0+ of aws-sdk as it has broken our instrumentation and mock server
- fixed version lockdown as it applies to both sqs in v2 and v3 of sdk
See #186

skip newer versions of sqs library

---

README.md

* Updated README links to point to new forum link due to repolinter ruleset change
Part of NR-122470

chore: update explorer hub links in readme

---

.github/workflows/smoke-tests.yml
THIRD_PARTY_NOTICES.md
package-lock.json
package.json
tests/smoke/v3/client-s3.test.js
tests/smoke/v3/s3-presigned-url.test.js
third_party_manifest.json

Realized our smoke tests pin the aws version so we can't test newer versions. Also logging it out.

ci: updated smoke tests to run npm install to get latest and console log the version so we know what is being tested in CI

---

nr-hooks.js
tests/versioned/v3/client-dynamodb.tap.js
tests/versioned/v3/lib-dynamodb.tap.js
tests/versioned/v3/sns.tap.js

* Fixed instrumentation in AWS 3.363.0.
Closes #194
AWS decided to rename their smithy client package to be [`@smithy` scoped](https://github.com/aws/aws-sdk-js-v3/pull/4873).  Thankfully this was a quick fix.

Fix instrumentation in 3.363.0 of aws sdk

---

tests/versioned/v3/package.json

Yet another aws sdk release broke things.  [3.377.0](https://github.com/aws/aws-sdk-js-v3/issues/5014) is not usable so this PR skips it and preemptively includes future releases.

ci: skip version 3.377.0 of aws sdk packages as they are broken

---

lib/v3/dynamodb.js
lib/v3/smithy-client.js
lib/v3/sns.js
lib/v3/sqs.js
tests/versioned/v3/client-dynamodb.tap.js
tests/versioned/v3/sns.tap.js
tests/versioned/v3/sqs.tap.js

* Updated aws-sdk v3 instrumentation to only call `shim.setLibrary` and `shim.setDatastore` once instead of on every call to SQS, SNS, and DynamoDB.
Closes #218
You can see the details from my analysis [here](https://github.com/newrelic/node-newrelic-aws-sdk/issues/218#issuecomment-1843329089). Big thanks to @jsumners-nr for pointing me in the right direction from the start. It made for a quick fix, the tests were the tricky part. If you undid the code side the tests would fail as the relevant `setLibrary` or `setDatastore` would be called n times vs just once.

fix: Updated aws-sdk v3 instrumentation to only call `shim.setLibrary` and `shim.setDatastore` once instead of on every call to sqs/sns/dyanmodb

---

tests/versioned/v3/package.json

We had failing versioned tests runs on [main of the agent](https://github.com/newrelic/node-newrelic/actions/runs/7277973871/job/19831177371). I traced it back to a change in 3.477.0 of [@aws-sdk/client-dynamodb](https://github.com/aws/aws-sdk-js-v3/pull/5284/files#diff-e15f91f7125819d820715e6b02e5bce9a1e7dd89c67a4ed348be8c6117396d49).  For now we will have to pin that peer dep until it becomes a problem.  These packages no longer follow semver so this is the nonsense we have to deal with at times.

test: pin peer dep of @aws-sdk/client-dynamodb so the older versions of @aws-sdk/lib-dynamodb pass

---

.github/PULL_REQUEST_TEMPLATE.md
.github/dependabot.yml
.github/workflows/prepare-release.yml
.github/workflows/validate-pr.yml
CONTRIBUTING.md
changelog.json

Since we are going to be doing more work in here I updated the release style to our conventional commit based workflow. I also added the validate-pr workflow and updated the PR template to no longer rely on convention in the PR description to derive changelogs.

ci: Updated prepare-release to use conventional commit based releases.

---

THIRD_PARTY_NOTICES.md
package.json
tests/versioned/aws-server-stubs/ai-server/index.js
tests/versioned/aws-server-stubs/index.js
tests/versioned/v3/bedrock-ai21.tap.js
tests/versioned/v3/bedrock-amazon.tap.js
tests/versioned/v3/bedrock-claude.tap.js
tests/versioned/v3/bedrock-cohere.tap.js
tests/versioned/v3/package.json
third_party_manifest.json

We are getting [CI failures](https://github.com/newrelic/node-newrelic/actions/runs/7292525346/job/19875464518#step:5:315) in the main repo because of the way versioned tests are run and the way the dependencies in this package are configured.
1. CI over there checkouts out a limited set of entities from this repo, and that list does not include the root `package.json`.
2. The versioned tests runner does not, as far as I can tell, honor the top-level `dependencies` list a versioned test's `package.json`. It only parses the `tests[N].dependencies` list.
3. Thus, we don't have any way to add the required dependencies for the AI mock server such that the mock server can continue to be exported along with the other mock servers. So we move the dependencies into the AI models tests …

test: Resolve issue with testing in main repo

---

tests/versioned/v3/package.json

Currently it is ok because there are only a few versions of `@smithy/eventstream-codec` and `@smity/util-utf8` but as this grows the combination of the the 3 libraries will make a lot of unnecessary test runs.

chore: use latest of test deps for bedrock versioned tests

---

lib/llm/bedrock-response.js
lib/llm/event.js
lib/llm/index.js
lib/llm/tracked-ids.js
lib/v3/bedrock.js
tests/unit/llm/bedrock-response.tap.js
tests/unit/llm/event.tap.js
tests/versioned/common.js
tests/versioned/v3/bedrock-chat-completions.tap.js

**Note**: In openai we keyed by the response id but AWS Bedrock lacks a response id.  However, they do have a unique id on every chat completion which is the request id.
Added `agent.llm.responses` for every chat completion message. Added a versioned tests that uses the agent APIs to `getLlmMessageIds` and `recordLlmFeedbackEvent` to verify it all works.  I also added temperature and max tokens to every request to ensure these are getting set on the LLM events.

feat: Added ability to store feedback ids by request id

---

lib/llm/event.js
lib/v3/bedrock.js
tests/unit/llm/event.tap.js

I tried to test what we have to date with our example app and it was failing because the custom event aggregator payload sizes were very big.  I realized it was because the constructionParams, bedrockCommand and bedrockResponse were included in the event.  The actual issue was really the agent in constructionParams but we should remove these props before sending off to the aggregator.

refactor: adds a serialize method to LlmEvent to remove the complex objects before enqueuing to the custom event aggregator

---

lib/llm/bedrock-response.js
lib/llm/chat-completion-message.js
lib/llm/chat-completion-summary.js
lib/llm/embedding.js
lib/llm/error.js
lib/llm/event.js
lib/llm/index.js
lib/v3/bedrock.js
tests/unit/llm/bedrock-response.tap.js
tests/unit/llm/chat-completion-message.tap.js
tests/unit/llm/chat-completion-summary.tap.js
tests/unit/llm/error.tap.js
tests/unit/llm/event.tap.js
tests/versioned/aws-server-stubs/ai-server/responses/ai21.js
tests/versioned/aws-server-stubs/ai-server/responses/amazon.js
tests/versioned/aws-server-stubs/ai-server/responses/claude.js
tests/versioned/aws-server-stubs/ai-server/responses/cohere.js
tests/versioned/aws-server-stubs/ai-server/responses/llama2.js
tests/versioned/common.js
tests/versioned/v3/bedrock-chat-completions.tap.js
tests/versioned/v3/bedrock-embeddings.tap.js

Added parsing of error responses, enqueueing transaction errors with additional custom attributes.  I'm not very happy with the edits in BedrockResponse.  I also had to tweak how the id is generated for certain models on the chat completion message as we will not have full response on error.  I also extracted more code into functions to combine the sequence of actions needed to handle chat completions and embeddings.
```
npm run unit
npm run versioned:major
```
Closes #225

feat: Added handling errors by adding additional attributes to the transaction errors.

---

lib/v3/bedrock.js
lib/v3/common.js
lib/v3/dynamodb.js
lib/v3/sns.js
lib/v3/sqs.js
tests/versioned/v3/lib-dynamodb.tap.js

Added `override: true` to middleware config for bedrock, dynamodb, sns and sqs. This allows us to override the middleware with the same name. 
Example use case: when using both `DynamoDBClient` and `DynamoDBDocumentClient` in the same project, a duplicate middleware name error is thrown. 
Added versioned test. 
Closes issue https://github.com/newrelic/node-newrelic/issues/2071

fix: Added override setting to middleware configuration

---

.github/workflows/ci-workflow.yml

We had an issue where some jobs are using `npm ci`, specifically Create Release.  It failed because the lock file was out of sync. Most of our repos run `npm ci` to install deps so this PR updates the CI job to do that instead of npm install.

ci: Updated CI workflows to run `npm ci` instead of `npm install` to catch package-lock.json being out of sync

---

lib/llm/bedrock-response.js
lib/llm/chat-completion-summary.js
lib/llm/embedding.js
lib/llm/event.js
lib/llm/stream-handler.js
tests/unit/llm/bedrock-response.tap.js
tests/unit/llm/chat-completion-message.tap.js
tests/unit/llm/chat-completion-summary.tap.js
tests/unit/llm/embedding.tap.js
tests/unit/llm/event.tap.js
tests/unit/llm/stream-handler.tap.js
tests/versioned/common.js
tests/versioned/v3/bedrock-chat-completions.tap.js
tests/versioned/v3/bedrock-embeddings.tap.js

Removed attributes around legacy token counts on summary. I also fixed the embedding event to only calculate token_count if callabck is specified.  Lastly, removed `transaction_id` from all events.
Closes #265

chore: Removed unused attributes on LlmChatCompletionSummary and LlmEmbedding

---

lib/util.js
lib/v2/dynamodb.js
lib/v2/sns.js
lib/v2/sqs.js
lib/v3/bedrock.js
lib/v3/dynamodb.js
lib/v3/sns.js
lib/v3/sqs.js
tests/unit/util.tap.js
tests/versioned/v3/bedrock-chat-completions.tap.js
tests/versioned/v3/package.json

This reverts commit 94de4208ebbf1161c2c2aaf66aced97a45c610b8.
We made a breaking change that affected customers on versions of agent < 11.11.0 and released as a minor.  Due to "reasons" we're backing this change out and plan on issuing a patch release to fix customers doing clean installs of agent < 11.11.0.  We have folded all of this code into the agent as of 11.16.0. 
I also verified that backing this out will not affect customers running 11.15.0 which removed constructing specs in the agent by going to the `11.15.0` tag and adding this branch into versioned external
```diff --git a/test/versioned-external/external-repos.js b/test/versioned-external/external-repos.js
index 15f625fa3..c52fffd9a 100644
--- a/test/versioned-external/external-repos.js
+++ …
```

chore: Revert "refactor: Updated aws sdk instrumentation to construct specs at instrumentation (#259)"
